name: carlogix_mobile
description: "A car service management application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  provider: ^6.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Updated version

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"  # Path to your logo file
  remove_alpha_ios: true  # Optional: removes transparency for iOS icons
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
