// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCarhOGed17AF45wG_upAYxfisVzA3yVBs',
    appId: '1:486852871413:web:25bedde198faa366dd71bc',
    messagingSenderId: '486852871413',
    projectId: 'carlogix-auth',
    authDomain: 'carlogix-auth.firebaseapp.com',
    storageBucket: 'carlogix-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP5myquCtW-K4zaUf-nye6VRBVFlmPdVk',
    appId: '1:486852871413:android:f0304bbe93cc9c1edd71bc',
    messagingSenderId: '486852871413',
    projectId: 'carlogix-auth',
    storageBucket: 'carlogix-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpEKiJ6oBVkhf4rSl90Nf-pqAhvwEA0Ts',
    appId: '1:486852871413:ios:8184c7433f3f6a2ddd71bc',
    messagingSenderId: '486852871413',
    projectId: 'carlogix-auth',
    storageBucket: 'carlogix-auth.firebasestorage.app',
    iosBundleId: 'com.example.carlogixMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpEKiJ6oBVkhf4rSl90Nf-pqAhvwEA0Ts',
    appId: '1:486852871413:ios:8184c7433f3f6a2ddd71bc',
    messagingSenderId: '486852871413',
    projectId: 'carlogix-auth',
    storageBucket: 'carlogix-auth.firebasestorage.app',
    iosBundleId: 'com.example.carlogixMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCarhOGed17AF45wG_upAYxfisVzA3yVBs',
    appId: '1:486852871413:web:a8c250554d3d8279dd71bc',
    messagingSenderId: '486852871413',
    projectId: 'carlogix-auth',
    authDomain: 'carlogix-auth.firebaseapp.com',
    storageBucket: 'carlogix-auth.firebasestorage.app',
  );
}
